### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by berliniq** [reiryuki/Miui-Clock-Magisk-Module#1]
hi .. now i have 2 clocks (system clock and new clock)
the new clock keeps crashing and says (clock keeps stopping).. should i remove the original from the phone to fix this ?

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except AML)
4) Full logcat #logcat
5) Z folder #zscript

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

**Comment by kristibektashi** [comment]
I have been experiencing the same bug. I opened a separate issue for it but it got closed.
