### ISSUE TITLE
App crashes when alarm rings

### ISSUE THREAD

**Issue by kristibektashi** [reiryuki/Miui-Clock-Magisk-Module#2]
I have recently installed a custom rom alongside Magisk on my device. However, I wanted to use the stock Miui clock app instead of the Google Clock that is included with my rom. However, the clock crashes every time the alarm rings and sometimes a "Clock keeps stopping" dialog is shown. This is clearly a major problem since I will not be able to wake up if the alarm crashes and doesn't ring. The Google Clock app that is included with my rom is working fine, so this has to be an issue with the module.

Device: Xiaomi Redmi Note 8T (willow)
ROM: [Pixel Experience 13 Plus (2023-02-21)](https://forum.xda-developers.com/t/rom-13-official-ginkgo-willow-pixelexperience-13.4494293/)
Custom Kernel: [Meow Kernel r9 (2023-03-04)](https://forum.xda-developers.com/t/kernel-unified-r-s-t-meow-kernel.4536389/) (although I believe this happened even before I installed the custom kernel)
Custom Recovery: [PBRP 3.1.0-20211216-0545](https://forum.xda-developers.com/t/recovery-official-pbrp-pitch-black-recovery.4233595/)
Magisk: f470988f-delta (25210)
Magisk Modules: Miui Core v4.10, Miui Clock v0.5

I have done the steps specified in the bug report guide (disable modules, logcat, etc) but I have sent them to you in a private Telegram message along with a video showcasing the bug because I don't want to post it here in case there is any personal information in it.

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.

**Comment by kristibektashi** [comment]
> I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.

I did send it to the author but in a private message on telegram because I don't want to expose personal information. Do you even read the post or do you just blindly copy - paste a message?

**Comment by kristibektashi** [comment]
I request this to be repopened
